VCST-1808: back in stock module
VirtoCommerce/vc-frontend pull request #1358
Opened 2024-10-07 08:59 UTC by mihey8800

## Description

## References
### Jira-link:

### Artifact URL:

2024-10-07 09:48 UTC, NaMax66 requested changes

2024-10-07 09:48 UTC, NaMax66 commented on client-app/core/utilities/line-items/index.ts
> +function prepareItemPrices(item: AnyLineItemType | Product) {
extend AnyLineItemType.

2024-10-07 09:48 UTC, NaMax66 commented on client-app/modules/quotes/useUserQuotes.ts
> +const DEFAULT_ITEMS_PER_PAGE = 9999;
return 10

2024-10-07 09:48 UTC, NaMax66 commented on client-app/shared/back-in-stock/components/back-in-stock-notify-button.vue
> +import { globals } from "../../../core/globals";
import starts from \@

2024-10-07 09:48 UTC, NaMax66 commented on client-app/shared/catalog/components/product/variations-table.vue
> +function getStockQuantity(variation: Product) {
should be variation type

2024-10-07 09:48 UTC, NaMax66 commented on client-app/pages/account/back-in-stock-subscriptions.vue
> +    <BackButtonInHeader v-if="isMobile" @click="$router.back()" />
should work with $router.back without ()

2024-10-07 09:48 UTC, NaMax66 commented on client-app/pages/account/back-in-stock-subscriptions.vue
> +            <ProductSkeletonGrid v-for="i in actualPageRowsCount" :key="i" />
rename i -> index

2024-10-07 09:48 UTC, NaMax66 commented on client-app/shared/back-in-stock/components/back-in-stock-subscriptions-line-items.vue
> +        @remove="() => removeSingleItem(item.id)"
() => removeSingleItem(item.id) -> removeSingleItem(item.id)

2024-10-07 09:48 UTC, NaMax66 commented on client-app/shared/back-in-stock/composables/useBackInStockSubscriptions.ts
> +const DEFAULT_ITEMS_PER_PAGE = 9999;
why so large? Why not pagination?

2024-10-07 09:48 UTC, NaMax66 commented on client-app/pages/account/back-in-stock-subscriptions.vue
> +          await fetchProductsAndSubscriptions();
void fetchProductsAndSubscriptions()
no need to wait

2024-10-07 09:48 UTC, NaMax66 commented on client-app/pages/account/back-in-stock-subscriptions.vue
> +  itemsPerPage.value = 9999;
use constant for pagination. and not so large

2024-10-07 09:48 UTC, NaMax66 commented on client-app/pages/account/back-in-stock-subscriptions.vue
> +    await fetchProducts({ productIds: backInStockSubscriptions.value.map((item) => item.id!), itemsPerPage: 9999 });
use constant for pagination. and not so large

2024-10-08 03:33 UTC, mihey8800 commented on client-app/shared/back-in-stock/composables/useBackInStockSubscriptions.ts
> +const DEFAULT_ITEMS_PER_PAGE = 9999;
buisness rule

2024-10-09 05:01 UTC, goldenmaya commented on client-app/pages/account/back-in-stock-subscriptions.vue
> +              <WishlistLineItems
back-in-stock-subscriptions-line-items?

2024-12-11 10:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/VirtoCommerce/vc-frontend?pullRequest=1358) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/VirtoCommerce/vc-frontend?pullRequest=1358) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: OlegoO<br/>:x: mihey8800<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/VirtoCommerce/vc-frontend?pullRequest=1358) it.</sub>

2024-12-27 12:00 UTC, closed without merging

2024-12-27 12:01 UTC, NaMax66 commented
outdated