fix: make catalog url slug seo friendly
VirtoCommerce/vc-frontend pull request #1466
Opened 2024-11-20 07:33 UTC by Andrew-Orlov

## Description

Make catalog url slug SEO friendly

## References
### Jira-link:

https://virtocommerce.atlassian.net/browse/VCST-2278

### Artifact URL:
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.15.0-pr-1466-f77b-f77bfd84.zip

2024-11-21 13:27 UTC, Andrew-Orlov commented on client-app/shared/layout/components/header/_internal/bottom-header.vue
> +//const router = useRouter();
It will be removed later within backend improvements.

2024-11-21 14:23 UTC, NaMax66 commented on client-app/config/menu.json
>            "route": {
all "route" could be removed

2024-11-21 14:23 UTC, NaMax66 commented on client-app/shared/layout/components/header/_internal/bottom-header.vue
> +//const router = useRouter();
Remove the comment please. Really dont need it here

2025-01-16 06:38 UTC, goldenmaya requested changes

2025-01-16 06:38 UTC, goldenmaya commented on client-app/shared/layout/components/header/_internal/bottom-header.vue
> +        class="border-primary px-[0.8rem] py-[0.55rem] text-sm"
remove class, use size="lg" or any to resize button

2025-01-16 06:38 UTC, goldenmaya commented on client-app/shared/layout/components/header/_internal/bottom-header.vue
> +          class="font-bold uppercase tracking-wide text-[--header-bottom-link-color] hover:text-[--header-bottom-link-hover-color]"
Remove font-bold, uppercase, tracking-wide

2025-01-16 07:02 UTC, goldenmaya approved these changes, later dismissed

2025-01-16 08:05 UTC, NaMax66 approved these changes, later dismissed

2025-02-05 12:34 UTC, ivan-kalachikov commented on client-app/core/composables/useNavigations.ts
> +  if (["Category", "Product"].some((item) => matchedRouteNames.includes(item))) {
There is still the route with name "Catalog", right? Why do we need to remove that here?

2025-02-05 12:45 UTC, ivan-kalachikov commented on client-app/router/index.ts
> +      return next(getReturnUrlValue() || { name: "Home" });
also not clear enough to me why do we need to change `Catalog` to `Home` here?
and by the way - commend above the block says `// Make Dashboard the default Home page for authorized users`  - it's better to fix the comment to make it up-to-date

2025-02-05 12:54 UTC, ivan-kalachikov commented on client-app/shared/layout/components/header/_internal/bottom-header.vue
> +      <VcButton
Seems that by replacing `a` with `VcButton` you broke some logic, take a closer look at `toggleCatalogDropdown` function

2025-02-06 10:23 UTC, Andrew-Orlov commented on client-app/config/menu.json
> -            "name": "Catalog"
It was discussed 2 months ago. We need to remove hardcode anyway.

2025-02-06 10:24 UTC, Andrew-Orlov commented on client-app/core/composables/useNavigations.ts
> +  if (["Category", "Product"].some((item) => matchedRouteNames.includes(item))) {
Answered before

2025-02-06 10:36 UTC, Andrew-Orlov commented on client-app/router/index.ts
> +      return next(getReturnUrlValue() || { name: "Home" });
Customer will be redirected to Dashboard after login anyway if `from` was anonymous pages. In other cases - to the Home page.

2025-02-06 11:24 UTC, IrinaSer approved these changes

2025-02-06 11:43 UTC, ivan-kalachikov approved these changes

2025-02-06 12:17 UTC, merged