feat: extend vc-hexagon-icon component
VirtoCommerce/vc-frontend pull request #1467
Opened 2024-11-20 09:51 UTC by goldenmaya

## Description

## References
### Jira-link:

https://virtocommerce.atlassian.net/browse/VCST-2280
### Artifact URL:

2024-11-20 12:36 UTC, NaMax66 requested changes

2024-11-20 12:36 UTC, NaMax66 commented on client-app/ui-kit/components/atoms/hexagon-icon/vc-hexagon-icon.vue
> +  mask: url("/static/icons/polygon.svg");
Lets make it other way. The path should be dynamic and hashed. Ask GPT

2024-11-27 12:24 UTC, NaMax66 submitted a review, later dismissed

2024-12-05 08:21 UTC, NaMax66 approved these changes

2024-12-05 08:25 UTC, ivan-kalachikov approved these changes

2024-12-05 08:45 UTC, merged